name: Test and deploy
on:
  push:
    branches:
      - master
jobs:
  check:
    name: Test and deploy to lazywack
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      #      - name: Get specific changed files
      #        id: changed-files-specific
      #        uses: tj-actions/changed-files@v23
      #        with:
      #          files: |
      #            readme.md
      #            *.py
      #            templates
      #            config.json
      #            **/*.html
      #            **/*.py
      #            Dockerfile
      #            requirements.txt

      - name: Setting up temporary docker image
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'

        run: |
          v=$(docker rm bankid)
          docker build -t bankid .
          docker run -d -p 8080:8080 --name bankid bankid

      - name: Testing temporary container build
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
          url: http://bankid:8080/health

      - name: Clean up temporary
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        run: |
          V=$(docker kill bankid)
          B=($docker rm bankid)

      - name: Install SSH Key
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SECRET_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          if_key_exists: ignore

      - name: Adding known hosts
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        run: ssh-keyscan -p ${{secrets.SSH_SECRET_PORT }} -H ${{ secrets.SSH_SECRET_HOST }} >> ~/.ssh/known_hosts

      - name: "Deploying image"
        #       if: steps.changed-files-specific.outputs.only_changed == 'true'
        run: ssh ${{secrets.SSH_SECRET_HOST}} -p ${{secrets.SSH_SECRET_PORT}} "cd bankid/ && git pull && VAR=$(docker kill bankid) && S=$(docker rm bankid) && docker build -t bankid . && docker run -d -p 8080:8080 --network=host --name bankid bankid"

      - name: Testing live image
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
          url: https://lazywack.no:8080/health
