name: Test and deploy
on:
  push:
    branches:
      - master
jobs:
  check:
    name: Test and deploy to lazywack
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      #      - name: Get specific changed files
      #        id: changed-files-specific
      #        uses: tj-actions/changed-files@v23
      #        with:
      #          files: |
      #            readme.md
      #            *.py
      #            templates
      #            config.json
      #            **/*.html
      #            **/*.py
      #            Dockerfile
      #            requirements.txt

      - name: Testing build
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'

        run: |
          docker build -t bankid .
          docker run -d -p 8080:8080 --network=host --name bankid bankid

      - name: Testing response from api.
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
          url: http://localhost:8080/health

      - name: Setting up SSH 1
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SECRET_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          if_key_exists: ignore

      - name: Setting up SSH 2
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        run: ssh-keyscan -p ${{secrets.SSH_SECRET_PORT }} -H ${{ secrets.SSH_SECRET_HOST }} >> ~/.ssh/known_hosts

      - name: Stopping old container
        run: ssh ${{secrets.SSH_SECRET_HOST}} -p ${{secrets.SSH_SECRET_PORT}} "docker kill bankid"
      
      -name: Removing old container.
        run: ssh ${{secrets.SSH_SECRET_HOST}} -p ${{secrets.SSH_SECRET_PORT}} "docker rm bankid"

      - name: "Deploying new container"
        #       if: steps.changed-files-specific.outputs.only_changed == 'true'
        run: ssh ${{secrets.SSH_SECRET_HOST}} -p ${{secrets.SSH_SECRET_PORT}} "cd bankid/ && git pull && docker build -t bankid . && docker run -d -p 8080:8080 --network=host --name bankid bankid"

      - name: Testing live image
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
          url: https://bankid.lazywack.no/health

  cleanup:
    needs: [check]
    name: Cleanup
    runs-on: self-hosted
    steps:
      - name: Cleaning up temporary stuff.
        #        if: steps.changed-files-specific.outputs.only_changed == 'true'
        run: |
          if $(docker kill bankid 2>> /dev/null); then
            echo "Killed Bankid container"
          fi

          if $(docker rm bankid 2>>/dev/null); then
            echo "Removed bankid container."
          fi
